CREATE TABLE IF NOT EXISTS STUDENT(
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER
);

INSERT INTO STUDENT(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('111', 'RAM', 'DELHI', '******','18'),
('222', 'SUJIT', 'GURAGAON', '******','21'),
('333', 'RAHUL', 'KOLKATA', '******','20'),
('444', 'RAVI', 'DELHI', '******','20'),
('555', 'RAMESH', 'GURAGAON', '******','24');

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';

SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

SELECT* FROM STUDENT WHERE NAME='RAM' OR NAME='SUJIT';

SELECT* FROM STUDENT WHERE NAME ='RAM' OR AGE =20;

SELECT* FROM STUDENT WHERE AGE =18 AND (NAME='RAM' OR NAME='RAMESH');